name: Check Package

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          version: "0.7.9"

      - name: Set up Python
        run: uv python install

      - name: Install
        run: uv sync --locked --all-extras --dev

      - name: Ruff
        run: uv run ruff check src/photoutils
      
      - name: Mypy
        run: uv run mypy src/photoutils
